//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndirectedGraphWebServices.DataLoaderSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataLoaderSvc.IDataLoaderWS")]
    public interface IDataLoaderWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWS/DataLoadXml", ReplyAction="http://tempuri.org/IDataLoaderWS/DataLoadXmlResponse")]
        void DataLoadXml(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWS/DataLoadXml", ReplyAction="http://tempuri.org/IDataLoaderWS/DataLoadXmlResponse")]
        System.Threading.Tasks.Task DataLoadXmlAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataLoaderWSChannel : UndirectedGraphWebServices.DataLoaderSvc.IDataLoaderWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataLoaderWSClient : System.ServiceModel.ClientBase<UndirectedGraphWebServices.DataLoaderSvc.IDataLoaderWS>, UndirectedGraphWebServices.DataLoaderSvc.IDataLoaderWS {
        
        public DataLoaderWSClient() {
        }
        
        public DataLoaderWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataLoaderWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataLoaderWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataLoaderWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DataLoadXml(string path) {
            base.Channel.DataLoadXml(path);
        }
        
        public System.Threading.Tasks.Task DataLoadXmlAsync(string path) {
            return base.Channel.DataLoadXmlAsync(path);
        }
    }
}
